export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST'
export const FETCH_ITEMS_FULLFILLED = 'FETCH_ITEMS_FULLFILLED'
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE'

export const CREATE_ITEM_REQUEST = 'CREATE_ITEM_REQUEST'
export const CREATE_ITEM_DONE = 'CREATE_ITEM_DONE'
export const CREATE_ITEM_ERROR = 'CREATE_ITEM_ERROR'
export const CREATE_ITEM_CLOSE = 'CREATE_ITEM_CLOSE'

export const SELECT_ITEM_DATA = 'SELECT_ITEM_DATA'
export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST'
export const UPDATE_ITEM_DONE = 'UPDATE_ITEM_DONE'
export const UPDATE_ITEM_ERROR = 'UPDATE_ITEM_ERROR'
export const UPDATE_ITEM_CLOSE = 'UPDATE_ITEM_CLOSE'


export const SELECT_MULTI_ROWS = 'SELECT_MULTI_ROWS'
export const DELETE_ITEM_BY_KEYS = 'DELETE_ITEM_BY_KEYS'
export const DELETE_ITEM_DONE = 'DELETE_ITEM_DONE'
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR'
export const DELETE_ITEM_CLOSE = 'DELETE_ITEM_CLOSE'

export const FETCH_FIELDS = 'FETCH_FIELDS'
export const FETCH_FIELDS_ERROR = 'FETCH_FIELDS_ERROR'



